[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[rpc_endpoints]
base_mainnet = "https://sparkling-wispy-owl.base-mainnet.quiknode.pro/ea71080fa444effed8eec4c8424a2c636b89c554/"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "BASESCAN_API_KEY" }
